# Load required packages

In [1]:
import pandas as pd
import numpy as np

# validation strategy 
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import cross_val_score
from sklearn.utils import shuffle

# models
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

# error measure/metrics
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import classification_report

# Load Datasets - cleaned and one-hot encoded

In [2]:
# load epilepsy dataset 
epilepsy = pd.read_csv("./Datasets/OneHotEpilepsyCleaned.csv", sep= ',', decimal= '.', on_bad_lines = 'error', skip_blank_lines=False)

# load dementia dataset 
dementia = pd.read_csv("./Datasets/OneHotDementiaCleaned.csv", sep= ',', decimal= '.', on_bad_lines = 'error', skip_blank_lines=False)

# Check data loaded is correct

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
epilepsy.head()

,Age,Weight,Height,Seizure Frequency,Seizure Duration,Epilepsy Type,Gender_Female,Gender_Male,Gender_Other,Medication Status_Not on Medication,Medication Status_On Medication,Alcohol or Drug Use_No,Alcohol or Drug Use_Yes,EEG Abnormality Detected_No,EEG Abnormality Detected_Yes,MRI/CT Scan Result_Abnormal,MRI/CT Scan Result_Normal,MRI/CT Scan Result_Not Done,Seizure Type_Absence,Seizure Type_Focal,Seizure Type_Generalized,Seizure Type_Tonic-Clonic,Aura Before Seizure_No,Aura Before Seizure_Yes,Loss of Consciousness_No,Loss of Consciousness_Yes,Muscle Stiffness_No,Muscle Stiffness_Yes,Jerky Movements_No,Jerky Movements_Yes,Postictal Confusion_No,Postictal Confusion_Yes,Blank Stare Episodes_No,Blank Stare Episodes_Yes,Eye Rolling_No,Eye Rolling_Yes,Stress or Anxiety Before Episode_No,Stress or Anxiety Before Episode_Yes,Lack of Sleep Before Episode_No,Lack of Sleep Before Episode_Yes,Flashing Lights Sensitivity_No,Flashing Lights Sensitivity_Yes,Loud Sound Sensitivity_No,Loud Sound Sensitivity_Yes,Missed Medication_No,Missed Medication_Yes,Family History of Epilepsy_No,Family History of Epilepsy_Yes,Head Injury History_No,Head Injury History_Yes,Brain Tumor_No,Brain Tumor_Yes,History of Stroke_No,History of Stroke_Yes,Genetic Disorder_No,Genetic Disorder_Yes,Developmental Delay (in Children)_No,Developmental Delay (in Children)_Yes
0,15,48.3,168.2,1,60,Generalised,False,True,False,False,True,False,True,False,True,False,True,False,False,False,False,True,True,False,False,True,True,False,False,True,False,True,True,False,False,True,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,False,True
1,36,44.8,156.2,3,30,Generalised,True,False,False,False,True,True,False,False,True,True,False,False,False,False,False,True,False,True,True,False,False,True,False,True,True,False,False,True,False,True,False,True,True,False,True,False,False,True,False,True,False,True,True,False,True,False,True,False,True,False,True,False
2,32,70.4,180.4,0,60,Focal,True,False,False,True,False,True,False,False,True,False,False,True,False,True,False,False,False,True,False,True,True,False,False,True,False,True,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,True,False,True,False,True,False,True,False,True,False
3,29,54.5,161.7,1,60,Generalised,False,True,False,False,True,True,False,False,True,False,False,True,False,False,False,True,True,False,False,True,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False,False,True,True,False,False,True,True,False,False,True,True,False,True,False,True,False
4,18,62.1,168.0,1,30,Generalised,False,True,False,False,True,True,False,False,True,True,False,False,False,False,False,True,False,True,False,True,True,False,False,True,False,True,False,True,True,False,False,True,False,True,False,True,True,False,True,False,False,True,True,False,True,False,True,False,True,False,True,False

In [5]:
pd.reset_option('display.max_columns')

In [6]:
dementia.head()

,Group,Visit,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF,M/F_F,M/F_M
0,Nondemented,1,87,14,2.0,27.0,0.0,1987,0.696,0.883,False,True
1,Nondemented,2,88,14,2.0,30.0,0.0,2004,0.681,0.876,False,True
2,Nondemented,1,88,18,3.0,28.0,0.0,1215,0.710,1.444,True,False
3,Nondemented,2,90,18,3.0,27.0,0.0,1200,0.718,1.462,True,False
4,Nondemented,1,80,12,4.0,28.0,0.0,1689,0.712,1.039,False,True

# Data Science Problems

In this section, we will solve two classification problems. The problems are:
1. Epilepsy Type Classification with the Epilepsy Dataset
2. Dementia Group Classification with the Dementia Dataset

The Epilepsy Classification is a binary classification which consist of labels Focal and Generalised. The Dementia Classification is a multiclass classification which has three labels, non-demented, demented and converted. 

The machine learning models that will be used are Decision Tree and Logistic Regression The training steps are documented below. This includes validation strategy and evaluation methods. We will start with Decision Tree and move on with Logistic Regression

# Prepare data

## Epilepsy Dataset

In [7]:
# get features data
X_epi = epilepsy.drop('Epilepsy Type', axis=1)
# get labels
y_epi = epilepsy['Epilepsy Type']

In [8]:
X_epi.head()

,Age,Weight,Height,Seizure Frequency,Seizure Duration,Gender_Female,Gender_Male,Gender_Other,Medication Status_Not on Medication,Medication Status_On Medication,...,Head Injury History_No,Head Injury History_Yes,Brain Tumor_No,Brain Tumor_Yes,History of Stroke_No,History of Stroke_Yes,Genetic Disorder_No,Genetic Disorder_Yes,Developmental Delay (in Children)_No,Developmental Delay (in Children)_Yes
0,15,48.3,168.2,1,60,False,True,False,False,True,...,True,False,True,False,True,False,True,False,False,True
1,36,44.8,156.2,3,30,True,False,False,False,True,...,True,False,True,False,True,False,True,False,True,False
2,32,70.4,180.4,0,60,True,False,False,True,False,...,True,False,True,False,True,False,True,False,True,False
3,29,54.5,161.7,1,60,False,True,False,False,True,...,True,False,False,True,True,False,True,False,True,False
4,18,62.1,168.0,1,30,False,True,False,False,True,...,True,False,True,False,True,False,True,False,True,False

In [11]:
# check shape of data 
print(f'data: {X_epi.shape}, label: {y_epi.shape}')

data: (621, 57), label: (621,)

In [13]:
X_train_epilepsy, X_test_epilepsy, y_train_epilepsy, y_test_epilepsy = train_test_split(X_epi, y_epi, test_size = 0.2, random_state = 0, stratify = y_epi)

In [14]:
# check shape of train and test data set 
print(f'X_train\t: {X_train_epilepsy.shape}, y_train\t: {y_train_epilepsy.shape}\nX_test\t: {X_test_epilepsy.shape}, y_test\t: {y_test_epilepsy.shape}')

X_train	: (496, 57), y_train	: (496,)
X_test	: (125, 57), y_test	: (125,)

## Dementia Dataset

In [17]:
# get features data
X_deme = dementia.iloc[:,1:]
# get labels
y_deme = dementia['Group']

In [18]:
# check shape of data 
print(f'data: {X_deme.shape}, label: {y_deme.shape}')

data: (354, 11), label: (354,)

In [19]:
X_train_dementia, X_test_dementia, y_train_dementia, y_test_dementia = train_test_split(X_deme, y_deme, test_size = 0.2, random_state = 0, stratify = y_deme)

In [20]:
# check shape of train and test data set 
print(f'X_train\t: {X_train_dementia.shape}, y_train\t: {y_train_dementia.shape}\nX_test\t: {X_test_dementia.shape}, y_test\t: {y_test_dementia.shape}')

X_train	: (283, 11), y_train	: (283,)
X_test	: (71, 11), y_test	: (71,)

# Decision Tree

## Finding best parameters using cross validation
To prevent overfitting which is common for a decision tree, parameters 
- "max_depth"
- "min_samples_split"
- "min_samples_leaf"

will be fine tuned. To find the best set of parameters, the best average score across a Stratified 10-fold cross validation will be considered and unique pairs of {"max_depth", "min_sample_split", "min_samples_leaf"} will be used. 

Parameter criterion and max_features is set to default which uses 'gini impurity' and the square root of total no. of features respectively[1]. max_features is set to default because sqrt(16) = 4 which is 25% of the total no. of features in the dry bean dataset. The recommendation is to check up to 30-40%[2]. 

- [1] https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html
- [2] Practical data science week 4 slides

## Define a function to find best parameters for decision tree

In [21]:
def find_best_params_DT(X_train, y_train):
    # set of values for each parameter
    max_depth_vals = [5, 7, 10, 12, 15, 17]
    min_samples_split_vals = [2, 5, 10, 20, 50, 100]
    min_samples_leaf_vals = [1, 2, 3, 5, 10, 20]
    
    max_depth_his = list()
    min_samples_his = list()
    min_leafs_his = list()
    corr_avg = list() 
    
    for max_depth in max_depth_vals:
        for min_sample in min_samples_split_vals: 
            for min_leaf in min_samples_leaf_vals: 
                acc_scores = list() 
    
                # instance of Decision Tree for each parameter set
                dt_clf = DecisionTreeClassifier(max_depth = max_depth, min_samples_split = min_sample, min_samples_leaf = min_leaf)
                
                # get average scores of each k fold 
                acc_scores = cross_val_score(dt_clf, X_train, y_train, cv = 10, scoring = 'accuracy')
                
                # find average score across all folds 
                avg_score = acc_scores.mean()
        
                print(f'With max_depth={max_depth}, min_samples_split={min_sample}, and min_samples_leaf={min_leaf}, the average accurary is {avg_score}')
                
                max_depth_his.append(max_depth)
                min_samples_his.append(min_sample)
                min_leafs_his.append(min_leaf)
                corr_avg.append(avg_score)
    
    return max_depth_his, min_samples_his, min_leafs_his, corr_avg

## Epilepsy Type Classification

In [22]:
max_depth_his, min_samples_his, min_leafs_his, corr_avg = find_best_params_DT(X_train_epilepsy, y_train_epilepsy)

With max_depth=5, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8869387755102041
With max_depth=5, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8850204081632652
With max_depth=5, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8889387755102041
With max_depth=5, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.882938775510204
With max_depth=5, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=5, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.9132244897959184
With max_depth=5, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8869387755102041
With max_depth=5, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.8870204081632653
With max_depth=5, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8869387755102041
With max_depth=5, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.880938775510204
With max_depth=5, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=5, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.9091836734693878
With max_depth=5, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8869387755102041
With max_depth=5, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.8849387755102042
With max_depth=5, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8869387755102041
With max_depth=5, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.882938775510204
With max_depth=5, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=5, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.9112244897959183
With max_depth=5, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.872938775510204
With max_depth=5, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8769387755102039
With max_depth=5, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.872938775510204
With max_depth=5, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.870938775510204
With max_depth=5, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8911020408163266
With max_depth=5, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.9091428571428573
With max_depth=5, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=5, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8869387755102041
With max_depth=7, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.882938775510204
With max_depth=7, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8869795918367348
With max_depth=7, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.880938775510204
With max_depth=7, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=7, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.9111836734693879
With max_depth=7, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.880857142857143
With max_depth=7, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.8808979591836733
With max_depth=7, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8808979591836735
With max_depth=7, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8769387755102039
With max_depth=7, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8911020408163266
With max_depth=7, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.9152653061224492
With max_depth=7, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8909795918367347
With max_depth=7, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.8869795918367348
With max_depth=7, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8930204081632654
With max_depth=7, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.880938775510204
With max_depth=7, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=7, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.9112244897959183
With max_depth=7, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.872938775510204
With max_depth=7, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8769387755102039
With max_depth=7, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.8769387755102039
With max_depth=7, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.870938775510204
With max_depth=7, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8951020408163265
With max_depth=7, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.9111836734693879
With max_depth=7, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=7, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8929795918367347
With max_depth=10, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8911428571428572
With max_depth=10, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8828979591836734
With max_depth=10, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8769387755102039
With max_depth=10, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8911020408163266
With max_depth=10, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.9132244897959184
With max_depth=10, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8950204081632652
With max_depth=10, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.8788979591836735
With max_depth=10, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.882938775510204
With max_depth=10, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8769387755102039
With max_depth=10, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=10, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.9112244897959183
With max_depth=10, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8909795918367347
With max_depth=10, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.8829795918367347
With max_depth=10, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8890204081632653
With max_depth=10, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.878938775510204
With max_depth=10, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8951020408163265
With max_depth=10, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.9071428571428571
With max_depth=10, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.872938775510204
With max_depth=10, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8769387755102039
With max_depth=10, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.872938775510204
With max_depth=10, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.870938775510204
With max_depth=10, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=10, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.9152653061224492
With max_depth=10, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=10, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8869387755102041
With max_depth=12, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8688571428571429
With max_depth=12, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.882938775510204
With max_depth=12, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.878938775510204
With max_depth=12, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8951020408163265
With max_depth=12, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.9111836734693878
With max_depth=12, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8890612244897959
With max_depth=12, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.880938775510204
With max_depth=12, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8849795918367347
With max_depth=12, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.880938775510204
With max_depth=12, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=12, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.9112244897959183
With max_depth=12, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8889795918367348
With max_depth=12, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.8849795918367347
With max_depth=12, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8870204081632653
With max_depth=12, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8769387755102039
With max_depth=12, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8951020408163265
With max_depth=12, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.9091836734693878
With max_depth=12, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8769387755102039
With max_depth=12, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.872938775510204
With max_depth=12, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.8769387755102039
With max_depth=12, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.870938775510204
With max_depth=12, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8971020408163264
With max_depth=12, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.9132244897959184
With max_depth=12, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=12, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8949795918367347
With max_depth=15, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.887061224489796
With max_depth=15, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.884938775510204
With max_depth=15, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.878938775510204
With max_depth=15, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8951020408163265
With max_depth=15, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.9132244897959184
With max_depth=15, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.887061224489796
With max_depth=15, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.8729387755102043
With max_depth=15, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8869387755102041
With max_depth=15, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8769387755102039
With max_depth=15, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8931020408163265
With max_depth=15, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.9132244897959184
With max_depth=15, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8909795918367347
With max_depth=15, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.8789795918367347
With max_depth=15, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8910204081632654
With max_depth=15, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8809795918367346
With max_depth=15, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8911020408163266
With max_depth=15, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.9111836734693879
With max_depth=15, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8769387755102039
With max_depth=15, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.872938775510204
With max_depth=15, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.8769387755102039
With max_depth=15, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.870938775510204
With max_depth=15, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8911020408163266
With max_depth=15, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.9132244897959184
With max_depth=15, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8910612244897959
With max_depth=15, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8910612244897959
With max_depth=17, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8849387755102043
With max_depth=17, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8849795918367347
With max_depth=17, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8869795918367347
With max_depth=17, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.878938775510204
With max_depth=17, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8931020408163265

In [23]:
max_ind = np.argmax(corr_avg)
best_max_depth = max_depth_his[max_ind]
best_min_samples_split = min_samples_his[max_ind]
best_min_leafs = min_leafs_his[max_ind]

print(f'The best acc is {corr_avg[max_ind]} with parameters:\n- max_depth\t\t=\t{best_max_depth}\n- min_samples_split\t=\t{best_min_samples_split}\n- min_samples_leaf\t=\t{best_min_leafs}')

The best acc is 0.9152653061224492 with parameters:
- max_depth		=	7
- min_samples_split	=	5
- min_samples_leaf	=	20

### Feature Selection/Hill climbing

Given Epilepsy dataset has 29 features, we can find the best set of features to train the final model along with the best set of paramters found. This is done using the hill climbing algorithm. Hill climbing randomly selects a feature from the dataset and adds it to a list where the features in the list is used to train the model. If the newly added feature improves the accuracy of the model, it is kept in the list. If it decreases or doesn't improve the accuracy, it is removed from the list.

This method works by having 19 different lists with range of values from 0 to n which represents each feature in the dataset and each list is randomly shuffled using 1 to 19 as the random_state parameter of the shuffle function[1]. It will go through all 19 of them to build the list that gives the best accuracy. This list will then be used to train the final model. Note that shuffle function may provide different shuffled lists when a kernel restarts. This affects the starting point and only moves towards a local minima rather than a global minimum.

- [1] https://scikit-learn.org/stable/modules/generated/sklearn.utils.shuffle.html

In [24]:
feas_set = list() 
scores = list() 

for i in range(1,20): 
    # to keep best features and score from them
    keep_feas_ind = []
    best_score = 0.0 
    
    # 16 features in epilepsy dataset
    fea_num = 29
    # create a new random list from the range of 1 to 15 by using a new random_state number 
    random_col_ind = shuffle(range(0,fea_num), random_state = i)

    print(f'random_state = {i}, col_ids = {random_col_ind}')
    for j in range(0, fea_num): 
        # add index of currently selected feature to the list
        keep_feas_ind.append(random_col_ind[j])
    
        # get bean features based off index listed in the list
        X_h = X_epi.iloc[:,keep_feas_ind]
    
        # create new train test split based off features in that list 
        X_train_h, X_test_h, y_train_h, y_test_h = train_test_split(X_h, y_epi, test_size = 0.2, random_state = 0, stratify = y_epi)
    
        # create instace of KNN with the best k and p value
        dt_clf = DecisionTreeClassifier(max_depth = best_max_depth, min_samples_split = best_min_samples_split, min_samples_leaf = best_min_leafs)
    
        # fit data into model 
        dt_fit = dt_clf.fit(X_train_h, y_train_h)
        
        # test model with test dataset and get the score - accurary 
        dt_score = dt_fit.score(X_test_h, y_test_h)
    
        # if newly added feature doesn't improve the model based off score, remove it from list 
        if (dt_score < best_score) or (dt_score == best_score): 
            keep_feas_ind.remove(random_col_ind[j])
        else: 
            # else keep it and update the new best score
            best_score = dt_score
            print("Score with " + str(len(keep_feas_ind)) + " Selected features: " + str(dt_score))

    feas_set.append(keep_feas_ind)
    scores.append(best_score)
    print(keep_feas_ind)
    print()

random_state = 1, col_ids = [14, 21, 18, 20, 25, 19, 3, 10, 23, 22, 4, 2, 24, 6, 17, 13, 7, 26, 1, 16, 0, 15, 28, 27, 9, 8, 12, 11, 5]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.888
[14, 18]

random_state = 2, col_ids = [1, 0, 14, 9, 20, 24, 16, 6, 3, 19, 27, 26, 12, 4, 10, 5, 21, 17, 2, 7, 25, 23, 18, 11, 22, 28, 13, 15, 8]
Score with 1 Selected features: 0.56
Score with 2 Selected features: 0.616
Score with 3 Selected features: 0.672
Score with 4 Selected features: 0.696
Score with 5 Selected features: 0.8
Score with 6 Selected features: 0.816
Score with 7 Selected features: 0.896
[1, 0, 24, 19, 27, 21, 18]

random_state = 3, col_ids = [18, 17, 12, 26, 15, 16, 13, 2, 1, 23, 14, 4, 22, 6, 7, 5, 20, 9, 11, 28, 19, 21, 0, 8, 27, 3, 25, 24, 10]
Score with 1 Selected features: 0.888
[18]

random_state = 4, col_ids = [11, 21, 27, 15, 20, 24, 17, 25, 19, 0, 3, 16, 10, 6, 12, 2, 4, 22, 13, 7, 9, 18, 28, 8, 1, 5, 23, 14, 26]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.608
Score with 3 Selected features: 0.728
Score with 4 Selected features: 0.824
Score with 5 Selected features: 0.888
Score with 6 Selected features: 0.92
[11, 21, 27, 24, 18, 1]

random_state = 5, col_ids = [11, 28, 24, 21, 26, 10, 2, 13, 25, 20, 27, 0, 17, 5, 1, 12, 19, 18, 23, 7, 4, 8, 9, 16, 22, 6, 15, 14, 3]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.728
Score with 3 Selected features: 0.832
Score with 4 Selected features: 0.888
Score with 5 Selected features: 0.896
[11, 28, 24, 18, 4]

random_state = 6, col_ids = [0, 27, 26, 6, 14, 18, 7, 5, 21, 17, 2, 8, 25, 4, 12, 19, 22, 23, 11, 1, 16, 24, 15, 13, 28, 20, 3, 9, 10]
Score with 1 Selected features: 0.552
Score with 2 Selected features: 0.664
Score with 3 Selected features: 0.888
Score with 4 Selected features: 0.896
[0, 27, 18, 23]

random_state = 7, col_ids = [2, 17, 1, 9, 11, 5, 18, 23, 24, 28, 12, 13, 16, 0, 27, 6, 26, 20, 10, 21, 8, 14, 7, 19, 3, 22, 25, 4, 15]
Score with 1 Selected features: 0.52
Score with 2 Selected features: 0.888
[2, 18]

random_state = 8, col_ids = [24, 0, 7, 18, 14, 4, 28, 1, 21, 6, 27, 11, 2, 15, 25, 22, 12, 10, 26, 13, 16, 23, 19, 8, 5, 9, 17, 20, 3]
Score with 1 Selected features: 0.704
Score with 2 Selected features: 0.888
Score with 3 Selected features: 0.896
[24, 18, 4]

random_state = 9, col_ids = [5, 9, 15, 4, 3, 7, 18, 19, 6, 2, 12, 13, 16, 10, 27, 11, 14, 0, 23, 17, 8, 20, 25, 1, 26, 24, 22, 21, 28]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.888
[5, 18]

random_state = 10, col_ids = [14, 7, 5, 2, 26, 20, 12, 13, 18, 1, 22, 6, 11, 23, 19, 3, 27, 21, 10, 25, 28, 8, 24, 16, 17, 0, 15, 4, 9]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.888
[14, 18]

random_state = 11, col_ids = [15, 8, 6, 26, 3, 11, 14, 21, 9, 5, 10, 22, 2, 4, 20, 28, 19, 0, 27, 24, 18, 7, 1, 12, 13, 23, 17, 16, 25]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.648
Score with 3 Selected features: 0.664
Score with 4 Selected features: 0.712
Score with 5 Selected features: 0.728
Score with 6 Selected features: 0.92
[15, 21, 5, 20, 28, 19]

random_state = 12, col_ids = [7, 15, 21, 9, 1, 19, 4, 14, 22, 20, 8, 18, 0, 10, 26, 28, 24, 13, 5, 25, 16, 12, 23, 3, 2, 17, 6, 27, 11]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.648
Score with 3 Selected features: 0.864
Score with 4 Selected features: 0.92
[7, 21, 19, 20]

random_state = 13, col_ids = [21, 15, 25, 1, 24, 8, 7, 28, 17, 22, 0, 19, 4, 11, 9, 26, 13, 5, 14, 23, 3, 12, 20, 2, 6, 27, 10, 16, 18]
Score with 1 Selected features: 0.648
Score with 2 Selected features: 0.704
Score with 3 Selected features: 0.824
Score with 4 Selected features: 0.888
[21, 24, 28, 18]

random_state = 14, col_ids = [2, 19, 3, 9, 1, 17, 15, 5, 14, 23, 20, 26, 21, 18, 4, 27, 0, 28, 13, 8, 16, 25, 10, 6, 7, 22, 12, 24, 11]
Score with 1 Selected features: 0.52
Score with 2 Selected features: 0.752
Score with 3 Selected features: 0.784
Score with 4 Selected features: 0.92
[2, 19, 3, 20]

random_state = 15, col_ids = [16, 14, 26, 27, 19, 18, 1, 2, 28, 6, 3, 25, 22, 9, 4, 20, 10, 24, 13, 17, 15, 11, 7, 0, 23, 5, 12, 21, 8]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.728
Score with 3 Selected features: 0.888
[16, 27, 18]

random_state = 16, col_ids = [6, 8, 12, 7, 19, 18, 21, 11, 3, 13, 26, 17, 22, 2, 10, 15, 24, 20, 27, 16, 0, 28, 23, 4, 1, 5, 25, 14, 9]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.8
Score with 3 Selected features: 0.888
[6, 19, 18]

random_state = 17, col_ids = [0, 18, 21, 11, 5, 24, 26, 19, 23, 25, 3, 2, 10, 8, 9, 27, 14, 1, 20, 12, 7, 4, 13, 16, 22, 6, 28, 17, 15]
Score with 1 Selected features: 0.552
Score with 2 Selected features: 0.888
Score with 3 Selected features: 0.896
[0, 18, 24]

random_state = 18, col_ids = [11, 0, 27, 20, 6, 13, 1, 3, 9, 12, 7, 22, 4, 16, 28, 23, 15, 25, 26, 21, 8, 2, 18, 14, 17, 5, 24, 19, 10]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.728
Score with 3 Selected features: 0.832
Score with 4 Selected features: 0.888
[11, 27, 23, 18]

random_state = 19, col_ids = [13, 3, 23, 6, 18, 25, 11, 24, 4, 17, 9, 16, 28, 0, 15, 7, 12, 22, 1, 5, 27, 26, 10, 20, 19, 8, 2, 21, 14]
Score with 1 Selected features: 0.584
Score with 2 Selected features: 0.704
Score with 3 Selected features: 0.888
Score with 4 Selected features: 0.896
[13, 23, 18, 4]

In [25]:
# get feature set with the highest score 
highest_score_ind = np.argmax(scores)
highest_score = scores[highest_score_ind]
best_features_index = feas_set[highest_score_ind]

print(f'The highest score is {highest_score}\nwith features: {X_epi.columns[best_features_index].tolist()}')

The highest score is 0.92
with features: ['Alcohol or Drug Use_Yes', 'Aura Before Seizure_No', 'Jerky Movements_No', 'Loss of Consciousness_Yes', 'Seizure Type_Focal', 'Weight']

In [26]:
# select the best features from the cleaned data
X_best_feas = X_epi.iloc[:, best_features_index]

# create new train test split based off best features
X_train_bf, X_test_bf, y_train_bf, y_test_bf = train_test_split(X_best_feas, y_epi, test_size = 0.2, random_state = 0, stratify = y_epi)

# create instace of KNN with the best max_depth, min_samples_split, and min_samples_leaf values
dt_clf = DecisionTreeClassifier(max_depth = best_max_depth, min_samples_split = best_min_samples_split, min_samples_leaf = best_min_leafs)

# fit data into model 
dt_fit = dt_clf.fit(X_train_bf, y_train_bf)

# predict with test data set 
dt_predicted_epilepsy = dt_fit.predict(X_test_bf)

## Dementia Type Classification

### Find the best parameters

In [27]:
max_depth_his, min_samples_his, min_leafs_his, corr_avg = find_best_params_DT(X_train_dementia, y_train_dementia)

With max_depth=5, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8482758620689654
With max_depth=5, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8305418719211822
With max_depth=5, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8344827586206897
With max_depth=5, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=5, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.862192118226601
With max_depth=5, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=5, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8584975369458128
With max_depth=5, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.8235221674876847
With max_depth=5, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.830911330049261
With max_depth=5, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=5, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8586206896551725
With max_depth=5, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=5, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8374384236453203
With max_depth=5, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.819704433497537
With max_depth=5, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8129310344827587
With max_depth=5, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=5, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8657635467980296
With max_depth=5, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=5, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8762315270935961
With max_depth=5, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8480295566502463
With max_depth=5, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.844950738916256
With max_depth=5, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.8661330049261083
With max_depth=5, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8586206896551725
With max_depth=5, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=5, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8725369458128078
With max_depth=5, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8512315270935961
With max_depth=5, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8619458128078819
With max_depth=5, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=5, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=5, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=7, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8380541871921183
With max_depth=7, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.7950738916256158
With max_depth=7, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8238916256157636
With max_depth=7, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=7, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8693349753694581
With max_depth=7, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=7, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8378078817733992
With max_depth=7, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.8023399014778325
With max_depth=7, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8237684729064039
With max_depth=7, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=7, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8657635467980296
With max_depth=7, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=7, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8408866995073891
With max_depth=7, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.7949507389162561
With max_depth=7, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8022167487684729
With max_depth=7, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=7, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8586206896551725
With max_depth=7, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=7, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8693349753694581
With max_depth=7, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8411330049261083
With max_depth=7, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.844950738916256
With max_depth=7, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.8661330049261083
With max_depth=7, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8586206896551725
With max_depth=7, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=7, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8725369458128078
With max_depth=7, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8512315270935961
With max_depth=7, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8619458128078819
With max_depth=7, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=7, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=7, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=10, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8306650246305418
With max_depth=10, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8020935960591131
With max_depth=10, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8237684729064039
With max_depth=10, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=10, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8657635467980296
With max_depth=10, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=10, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8339901477832512
With max_depth=10, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.7953201970443351
With max_depth=10, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.827216748768473
With max_depth=10, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=10, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8586206896551725
With max_depth=10, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=10, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8232758620689656
With max_depth=10, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.78435960591133
With max_depth=10, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8057881773399014
With max_depth=10, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8448275862068966
With max_depth=10, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.862192118226601
With max_depth=10, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=10, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8693349753694581
With max_depth=10, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8411330049261083
With max_depth=10, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.844950738916256
With max_depth=10, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.8661330049261083
With max_depth=10, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8586206896551725
With max_depth=10, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=10, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8725369458128078
With max_depth=10, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8512315270935961
With max_depth=10, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8619458128078819
With max_depth=10, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=10, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=10, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=12, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8306650246305418
With max_depth=12, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.8022167487684729
With max_depth=12, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8201970443349754
With max_depth=12, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=12, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.862192118226601
With max_depth=12, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=12, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8163793103448278
With max_depth=12, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.798768472906404
With max_depth=12, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8131773399014779
With max_depth=12, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=12, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.862192118226601
With max_depth=12, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=12, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8126847290640395
With max_depth=12, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.7807881773399015
With max_depth=12, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.7986453201970443
With max_depth=12, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=12, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8693349753694581
With max_depth=12, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=12, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8693349753694581
With max_depth=12, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8411330049261083
With max_depth=12, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.844950738916256
With max_depth=12, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.8661330049261083
With max_depth=12, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8693349753694581
With max_depth=12, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=12, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8725369458128078
With max_depth=12, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8512315270935961
With max_depth=12, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8619458128078819
With max_depth=12, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=12, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=12, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=15, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8273399014778325
With max_depth=15, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.798768472906404
With max_depth=15, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8201970443349754
With max_depth=15, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8483990147783251
With max_depth=15, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8693349753694581
With max_depth=15, min_samples_split=2, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=15, min_samples_split=5, and min_samples_leaf=1, the average accurary is 0.8233990147783252
With max_depth=15, min_samples_split=5, and min_samples_leaf=2, the average accurary is 0.7988916256157637
With max_depth=15, min_samples_split=5, and min_samples_leaf=3, the average accurary is 0.8201970443349754
With max_depth=15, min_samples_split=5, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=15, min_samples_split=5, and min_samples_leaf=10, the average accurary is 0.8657635467980296
With max_depth=15, min_samples_split=5, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=15, min_samples_split=10, and min_samples_leaf=1, the average accurary is 0.8232758620689656
With max_depth=15, min_samples_split=10, and min_samples_leaf=2, the average accurary is 0.78435960591133
With max_depth=15, min_samples_split=10, and min_samples_leaf=3, the average accurary is 0.8057881773399014
With max_depth=15, min_samples_split=10, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=15, min_samples_split=10, and min_samples_leaf=10, the average accurary is 0.8657635467980296
With max_depth=15, min_samples_split=10, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=15, min_samples_split=20, and min_samples_leaf=1, the average accurary is 0.8693349753694581
With max_depth=15, min_samples_split=20, and min_samples_leaf=2, the average accurary is 0.8411330049261083
With max_depth=15, min_samples_split=20, and min_samples_leaf=3, the average accurary is 0.844950738916256
With max_depth=15, min_samples_split=20, and min_samples_leaf=5, the average accurary is 0.8661330049261083
With max_depth=15, min_samples_split=20, and min_samples_leaf=10, the average accurary is 0.8657635467980296
With max_depth=15, min_samples_split=20, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=15, min_samples_split=50, and min_samples_leaf=1, the average accurary is 0.8725369458128078
With max_depth=15, min_samples_split=50, and min_samples_leaf=2, the average accurary is 0.8512315270935961
With max_depth=15, min_samples_split=50, and min_samples_leaf=3, the average accurary is 0.8619458128078819
With max_depth=15, min_samples_split=50, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=50, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=50, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=15, min_samples_split=100, and min_samples_leaf=1, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=100, and min_samples_leaf=2, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=100, and min_samples_leaf=3, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=100, and min_samples_leaf=5, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=100, and min_samples_leaf=10, the average accurary is 0.8796798029556652
With max_depth=15, min_samples_split=100, and min_samples_leaf=20, the average accurary is 0.8903940886699507
With max_depth=17, min_samples_split=2, and min_samples_leaf=1, the average accurary is 0.8517241379310345
With max_depth=17, min_samples_split=2, and min_samples_leaf=2, the average accurary is 0.7846059113300492
With max_depth=17, min_samples_split=2, and min_samples_leaf=3, the average accurary is 0.8236453201970443
With max_depth=17, min_samples_split=2, and min_samples_leaf=5, the average accurary is 0.8519704433497537
With max_depth=17, min_samples_split=2, and min_samples_leaf=10, the average accurary is 0.8586206896551725

In [28]:
max_ind = np.argmax(corr_avg)
best_max_depth = max_depth_his[max_ind]
best_min_samples_split = min_samples_his[max_ind]
best_min_leafs = min_leafs_his[max_ind]

print(f'The best acc is {corr_avg[max_ind]} with parameters:\n- max_depth\t\t=\t{best_max_depth}\n- min_samples_split\t=\t{best_min_samples_split}\n- min_samples_leaf\t=\t{best_min_leafs}')

The best acc is 0.8903940886699507 with parameters:
- max_depth		=	5
- min_samples_split	=	2
- min_samples_leaf	=	20

Given there are only 10 features in the Dementia dataset, hill climbing will not be used here.

### Train with best set of parameters

In [29]:
# create instace of KNN with the best max_depth, min_samples_split, and min_samples_leaf values
dt_clf = DecisionTreeClassifier(max_depth = best_max_depth, min_samples_split = best_min_samples_split, min_samples_leaf = best_min_leafs)

# fit data into model 
dt_fit = dt_clf.fit(X_train_dementia, y_train_dementia)

# predict with test data set 
dt_predicted_dementia = dt_fit.predict(X_test_dementia)

## Evaluation with classification report

### Epilepsy Classification

In [30]:
# confusion matrix
print(confusion_matrix(y_test_epilepsy, dt_predicted_epilepsy))

print(classification_report(y_test_epilepsy, dt_predicted_epilepsy))

[[49  3]
 [ 7 66]]
              precision    recall  f1-score   support

       Focal       0.88      0.94      0.91        52
 Generalised       0.96      0.90      0.93        73

    accuracy                           0.92       125
   macro avg       0.92      0.92      0.92       125
weighted avg       0.92      0.92      0.92       125

### Dementia Classification

In [31]:
# confusion matrix
print(confusion_matrix(y_test_dementia, dt_predicted_dementia))

print(classification_report(y_test_dementia, dt_predicted_dementia))

[[ 0  1  6]
 [ 0 26  0]
 [ 0  1 37]]
              precision    recall  f1-score   support

   Converted       0.00      0.00      0.00         7
    Demented       0.93      1.00      0.96        26
 Nondemented       0.86      0.97      0.91        38

    accuracy                           0.89        71
   macro avg       0.60      0.66      0.63        71
weighted avg       0.80      0.89      0.84        71

/opt/anaconda3/envs/py3_12_7/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/py3_12_7/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/anaconda3/envs/py3_12_7/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

#### ERROR NOTE:

Zero division warning error because the model has not classified a Converted correctly.

# Logistic Regression

In [37]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import accuracy_score

## Dementia Dataset

In [138]:
lr_d = LogisticRegression(solver='lbfgs', l1_ratio=0, max_iter=20000, random_state=0)

In [139]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_dementia)
X_test_scaled = scaler.transform(X_test_dementia)

In [140]:
lr_d.fit(X_train_scaled, y_train_dementia)

LogisticRegression(l1_ratio=0, max_iter=20000, random_state=0)

In [141]:
y_pred_d = lr_d.predict(X_test_scaled)
y_prob_d = lr_d.predict_proba(X_test_scaled)

In [142]:
print(f"Accuracy: {accuracy_score(y_test_dementia, y_pred_d):.2f}")
print("\nClassification Report:\n", classification_report(y_test_dementia, y_pred_d, target_names=dementia.Group.unique()))

Accuracy: 0.90

Classification Report:
               precision    recall  f1-score   support

 Nondemented       1.00      0.14      0.25         7
    Demented       0.96      1.00      0.98        26
   Converted       0.86      0.97      0.91        38

    accuracy                           0.90        71
   macro avg       0.94      0.71      0.71        71
weighted avg       0.91      0.90      0.87        71

In [128]:
y_prob_d

array([[4.31947897e-02, 4.62602964e-03, 9.52179181e-01],
       [4.40276681e-03, 9.95590659e-01, 6.57405717e-06],
       [4.69014091e-02, 1.24761245e-03, 9.51850978e-01],
       [5.38305312e-03, 4.51584653e-04, 9.94165362e-01],
       [3.43331926e-05, 9.99965608e-01, 5.89060438e-08],
       [6.87294798e-02, 3.70005581e-03, 9.27570464e-01],
       [4.18193117e-02, 9.33610245e-01, 2.45704428e-02],
       [1.32507316e-02, 1.40616886e-05, 9.86735207e-01],
       [5.81776313e-05, 9.99941785e-01, 3.78480493e-08],
       [3.88791614e-03, 9.95487043e-01, 6.25041300e-04],
       [4.21471086e-02, 9.54904590e-01, 2.94830164e-03],
       [2.28067751e-02, 2.13948575e-04, 9.76979276e-01],
       [3.92509290e-01, 5.38409774e-04, 6.06952301e-01],
       [1.32084936e-05, 9.99986755e-01, 3.69365225e-08],
       [5.59518776e-03, 4.04210653e-04, 9.94000602e-01],
       [2.92151636e-05, 9.99970712e-01, 7.28533465e-08],
       [3.11385792e-01, 6.62913444e-01, 2.57007643e-02],
       [1.28897463e-01, 8.63163744e-01, 7.93879300e-03],
       [1.06912044e-05, 9.99989271e-01, 3.74228419e-08],
       [3.64863023e-05, 9.99963504e-01, 9.30298652e-09],
       [1.17068857e-01, 7.82252530e-01, 1.00678614e-01],
       [2.44040248e-02, 2.48175704e-03, 9.73114218e-01],
       [2.36001999e-02, 5.20917460e-03, 9.71190626e-01],
       [3.78774276e-02, 5.51999317e-04, 9.61570573e-01],
       [3.92328076e-02, 5.78507041e-03, 9.54982122e-01],
       [2.24656863e-01, 8.18902301e-04, 7.74524234e-01],
       [7.63142982e-01, 1.90761474e-01, 4.60955433e-02],
       [1.18985386e-01, 5.37028153e-03, 8.75644333e-01],
       [6.27457758e-02, 2.67604260e-03, 9.34578182e-01],
       [9.57359541e-03, 2.09919283e-03, 9.88327212e-01],
       [2.40569697e-03, 9.96749902e-01, 8.44401050e-04],
       [2.24102291e-01, 1.55186465e-03, 7.74345845e-01],
       [1.23673410e-01, 1.51076618e-02, 8.61218928e-01],
       [4.36198721e-02, 3.93537747e-04, 9.55986590e-01],
       [1.67470104e-01, 6.51138734e-04, 8.31878757e-01],
       [3.96422961e-01, 5.01154825e-01, 1.02422214e-01],
       [1.71886130e-02, 7.16289970e-02, 9.11182390e-01],
       [4.18173331e-01, 5.18808056e-01, 6.30186132e-02],
       [4.99632882e-03, 1.30711938e-03, 9.93696552e-01],
       [1.05286780e-04, 9.99894620e-01, 9.29941434e-08],
       [6.27016821e-02, 6.94513901e-03, 9.30353179e-01],
       [3.59455377e-01, 6.20240211e-01, 2.03044119e-02],
       [2.53274551e-02, 1.64329963e-03, 9.73029245e-01],
       [3.48278373e-03, 9.96501888e-01, 1.53278394e-05],
       [9.57349046e-02, 8.68176473e-03, 8.95583331e-01],
       [7.24783906e-02, 2.43521275e-03, 9.25086397e-01],
       [1.25284103e-01, 1.47730144e-03, 8.73238595e-01],
       [6.46819310e-03, 9.90597469e-01, 2.93433768e-03],
       [5.84631072e-02, 9.39796282e-01, 1.74061094e-03],
       [1.15051531e-01, 8.11793553e-01, 7.31549160e-02],
       [1.40324862e-05, 9.99985936e-01, 3.19168106e-08],
       [8.06392504e-02, 8.03061384e-04, 9.18557688e-01],
       [1.08248568e-01, 1.09654473e-03, 8.90654888e-01],
       [2.47410985e-02, 9.74126155e-01, 1.13274682e-03],
       [9.50265386e-02, 9.06765504e-03, 8.95905806e-01],
       [5.34885179e-02, 4.74221503e-03, 9.41769267e-01],
       [2.32992473e-02, 7.89263978e-02, 8.97774355e-01],
       [1.76559346e-01, 2.75364962e-03, 8.20687004e-01],
       [2.86105981e-02, 4.97936431e-03, 9.66410038e-01],
       [1.76116326e-02, 1.00113119e-02, 9.72377055e-01],
       [1.55658719e-01, 1.57825827e-03, 8.42763023e-01],
       [2.39374025e-02, 2.41107294e-03, 9.73651525e-01],
       [9.85398807e-02, 4.73957522e-03, 8.96720544e-01],
       [1.25463433e-07, 9.99999875e-01, 1.38678181e-11],
       [2.75306620e-02, 1.02274375e-01, 8.70194963e-01],
       [2.81668456e-01, 1.54050235e-02, 7.02926520e-01],
       [1.99168277e-02, 9.78052102e-01, 2.03107057e-03],
       [1.27936350e-01, 3.65109332e-03, 8.68412557e-01],
       [5.05361744e-05, 9.99949428e-01, 3.56771680e-08],
       [1.79386506e-01, 3.45142778e-03, 8.17162066e-01],
       [3.74765495e-02, 1.55373448e-01, 8.07150002e-01]])

## Epilepsy Dataset

In [100]:
lr_e = LogisticRegression(solver='lbfgs', max_iter=600)

In [101]:
lr_e.fit(X_train_epilepsy, y_train_epilepsy)

LogisticRegression(max_iter=600)

In [102]:
y_pred_e = lr_e.predict(X_test_epilepsy)
y_prob_e = lr_e.predict_proba(X_test_epilepsy)

In [103]:
y_prob_e.shape
y_prob_e

array([[0.99263109, 0.00736891],
       [0.02655803, 0.97344197],
       [0.89652444, 0.10347556],
       [0.94670584, 0.05329416],
       [0.99341083, 0.00658917],
       [0.9256624 , 0.0743376 ],
       [0.93116323, 0.06883677],
       [0.01199094, 0.98800906],
       [0.9837261 , 0.0162739 ],
       [0.16425428, 0.83574572],
       [0.13771758, 0.86228242],
       [0.07297287, 0.92702713],
       [0.40737916, 0.59262084],
       [0.13169177, 0.86830823],
       [0.91762455, 0.08237545],
       [0.02226363, 0.97773637],
       [0.97848744, 0.02151256],
       [0.07806084, 0.92193916],
       [0.04786052, 0.95213948],
       [0.80420484, 0.19579516],
       [0.10269093, 0.89730907],
       [0.9323632 , 0.0676368 ],
       [0.99017249, 0.00982751],
       [0.01988233, 0.98011767],
       [0.98498545, 0.01501455],
       [0.24496073, 0.75503927],
       [0.96698439, 0.03301561],
       [0.83771906, 0.16228094],
       [0.01128457, 0.98871543],
       [0.98350426, 0.01649574],
       [0.99132443, 0.00867557],
       [0.081815  , 0.918185  ],
       [0.05498979, 0.94501021],
       [0.04369108, 0.95630892],
       [0.96818512, 0.03181488],
       [0.09771597, 0.90228403],
       [0.05049325, 0.94950675],
       [0.22083039, 0.77916961],
       [0.01671188, 0.98328812],
       [0.99638479, 0.00361521],
       [0.98541687, 0.01458313],
       [0.0549674 , 0.9450326 ],
       [0.08005841, 0.91994159],
       [0.34713508, 0.65286492],
       [0.02669581, 0.97330419],
       [0.01725953, 0.98274047],
       [0.98754735, 0.01245265],
       [0.96155203, 0.03844797],
       [0.02457061, 0.97542939],
       [0.01558343, 0.98441657],
       [0.94458551, 0.05541449],
       [0.4410971 , 0.5589029 ],
       [0.96071112, 0.03928888],
       [0.20463669, 0.79536331],
       [0.8414679 , 0.1585321 ],
       [0.01318172, 0.98681828],
       [0.01966423, 0.98033577],
       [0.97359099, 0.02640901],
       [0.04365136, 0.95634864],
       [0.01085867, 0.98914133],
       [0.93622889, 0.06377111],
       [0.69137365, 0.30862635],
       [0.02411215, 0.97588785],
       [0.02585761, 0.97414239],
       [0.90067278, 0.09932722],
       [0.13182174, 0.86817826],
       [0.01385309, 0.98614691],
       [0.02019896, 0.97980104],
       [0.94032274, 0.05967726],
       [0.10268964, 0.89731036],
       [0.05357949, 0.94642051],
       [0.0107817 , 0.9892183 ],
       [0.97728553, 0.02271447],
       [0.32321602, 0.67678398],
       [0.04361324, 0.95638676],
       [0.04818645, 0.95181355],
       [0.02626794, 0.97373206],
       [0.04052644, 0.95947356],
       [0.01628676, 0.98371324],
       [0.00806434, 0.99193566],
       [0.10270151, 0.89729849],
       [0.99848258, 0.00151742],
       [0.09533233, 0.90466767],
       [0.00292369, 0.99707631],
       [0.13817767, 0.86182233],
       [0.0497606 , 0.9502394 ],
       [0.03550703, 0.96449297],
       [0.00707742, 0.99292258],
       [0.33916799, 0.66083201],
       [0.94153242, 0.05846758],
       [0.04109994, 0.95890006],
       [0.02475272, 0.97524728],
       [0.05021529, 0.94978471],
       [0.80167981, 0.19832019],
       [0.98630249, 0.01369751],
       [0.09263206, 0.90736794],
       [0.2437911 , 0.7562089 ],
       [0.91822332, 0.08177668],
       [0.02228742, 0.97771258],
       [0.04524282, 0.95475718],
       [0.92708601, 0.07291399],
       [0.01022126, 0.98977874],
       [0.84809369, 0.15190631],
       [0.96534573, 0.03465427],
       [0.77735347, 0.22264653],
       [0.04163798, 0.95836202],
       [0.95358693, 0.04641307],
       [0.99561197, 0.00438803],
       [0.74373326, 0.25626674],
       [0.01221985, 0.98778015],
       [0.15611429, 0.84388571],
       [0.06325373, 0.93674627],
       [0.88420148, 0.11579852],
       [0.93839185, 0.06160815],
       [0.00759055, 0.99240945],
       [0.55433609, 0.44566391],
       [0.98320607, 0.01679393],
       [0.07640851, 0.92359149],
       [0.91813199, 0.08186801],
       [0.02009307, 0.97990693],
       [0.23818888, 0.76181112],
       [0.60020451, 0.39979549],
       [0.93280931, 0.06719069],
       [0.78198088, 0.21801912],
       [0.24356208, 0.75643792]])

In [95]:
X_test_epilepsy.shape

(125, 57)